package com.kodakestan.kodak.Exceptions.handler;

public enum ExceptionType {
    //internal Exception
    UNHANDLED_EXCEPTION(101),
    ERR_CONCURRENCY_FAILURE(102),
    ERR_ACCESS_DENIED(103),
    ERR_VALIDATION(104),
    ERR_METHOD_NOT_SUPPORTED(105),
    ERR_INTERNAL_SERVER_ERROR(106),

    //service Exception
    CATEGORY_PRODUCT_NOT_FOUND(201),
    ERR_BAD_REQUEST(202),
    CATEGORY_NOT_FOUND(203),
    BASKET_NOT_FOUND(204),
    PRODUCT_NOT_FOUND(205),
    ADDRESS_NOT_FOUND(206),
    ADVERTISE_TYPE_NOT_FOUND(207),
    ADVERTISEMENT_NOT_FOUND(208),
    BILL_NOT_FOUND(209),
    CAMPAIGN_NOT_FOUND(210),
    CAMPAIGN_WAS_EXPIRED(211),
    CAMPAIGN_COMMENT_NOT_FOUND(212),
    NO_COMMENT_ADDED(213),
    CAMPAIGN_IMAGE_NOT_FOUND(214),
    NO_IMAGE_ADDED(215),
    CAMPAIGN_TYPE_NOT_FOUND(216),
    THIS_COMMENT_DELETED(217),
    FILM_NOT_FOUND(218),
    CAMPAIGN_FILM_NOT_FOUND(219),
    NO_FILM_ADDED(220),
    MANUFACTURE_NOT_FOUND(221),
    NO_PRICE_ADDED(222),
    NOT_SCORE_ADDED(223),
    NO_SOCIAL_NETWORK_ADDED(224),
    VIEW_COUNTER_NOT_FOUND(225),
    NOT_ENOUGH_CREDIT(226),
    NOT_PERMISSION_FOR_ADVERTISEMENT(227),
    USER_NOT_FOUND(228),
    PAGE_OUT_OF_RANGE(229),
    COMMENT_NOT_FOUND(230),
    SOCIAL_NETWORK_NOT_FOUND(231),
    IMAGE_NOT_FOUND(232),
    DUPLICATE_VOTE_EXCEPTION(233),
    COMMENT_DUPLICATED(234),
    Out_OF_SIZE_IMAGE(235);
    private int code;

    ExceptionType(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }

}